### ISSUE TITLE
Add logspout-logstash

### ISSUE THREAD

**Issue by lokanx** [bertbaron/hassio-addons#30]
Hi!

This add-on seems very interesting but I miss logstash support.

Any chance you could add support for logspout-logstash? Planning to use it for sending logs to a remote ELK cluster via logstash. Or is there any easier option you know about?

https://github.com/looplab/logspout-logstash

Best regards

**Comment by bertbaron** [comment]
It should be possible to add, it is actually already included in the custom modules (https://github.com/gliderlabs/logspout/blob/master/custom/modules.go). I will have a look this weekend at how to include this in the build.

**Comment by lokanx** [comment]
Hi!

Great, thanks 👍

I think you only need to import it in modules.go, if don't missunderstand the documentation. And then release new versions. Like this:

package main

import (
  _ "github.com/looplab/logspout-logstash"
  _ "github.com/gliderlabs/logspout/transports/udp"
  _ "github.com/gliderlabs/logspout/transports/tcp"
)

**Comment by bertbaron** [comment]
I added the logstash adapter in a new release. I only did some basic testing, just to verify the adapter was included. If there are any issues please let me know.

**Comment by lokanx** [comment]
Hi!

It seems to work fine, log statements flowing in to ELK stack now.
Just need to reconfigure logstash to deal with json and I'm home

Just added a route like this: logstash+tcp://logstash.home.local:5000.

Thank for a swift fix 🥇 👍
