### ISSUE TITLE
Logs not accessible by add-on (insecure mode)?

### ISSUE THREAD

**Issue by moltob** [bertbaron/hassio-addons#50]
Hi, thanks for offering this addon to the community. It appears to be one of the few options that could work nicely to get logs out of HA.

I am trying to use it, but unfortunately, I think I am not getting any logs (in loki @ Grafana cloud) because I suspect that the addon is not able to access HA container logs in the first place. But that is just a guess.

This is the HA system state:

![image](https://github.com/bertbaron/hassio-addons/assets/6240478/5955b5c3-cd2f-4485-9f13-ac1d9116e5a7)

And this would be your addon's log:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2024/04/26 20:31:07 # logspout v3.2.14-hassio-3 by gliderlabs
2024/04/26 20:31:07 # adapters: multiline raw syslog tcp tls loki gelf udp logstash
2024/04/26 20:31:07 # options :
2024/04/26 20:31:07 persist:/data/routes
2024/04/26 20:31:07 Using Loki url: https://xxx:xxxxx@xxxx-xxxx-xxx.grafana.net/api/prom/push
2024/04/26 20:31:07 # jobs    : http[health,logs,routes]:80 pump routes
2024/04/26 20:31:07 # routes  :
#   ADAPTER     ADDRESS                         CONTAINERS      SOURCES OPTIONS
#   loki+https  xxxx-xxxx-xxx.grafana.net                               map[]
```

And that's it. I think I have read somewhere that I should be able to see logs here. Is that correct? The `CONTAINERS` column is empty, does that indicate an issue?

Thanks a lot!

**Comment by moltob** [comment]
Forgot to add: the addon _is_ running in unprotected mode:

![image](https://github.com/bertbaron/hassio-addons/assets/6240478/b07a73f5-c44d-43f6-940f-2f7852c96e2a)

**Comment by bertbaron** [comment]
Hi, the log is looking just fine, the messages themselves will not be logged in the Logspout log, just send through any route. Containers should also be empty, I think this will only be valid when filters are provided. My guess is that either sending the logs to the Loki endpoint fails or you are looking in the wrong place to find them.
To confirm or rule out the first option, you could enable debug logging with the following in the config (yaml format):
```yaml
env:
  - name: DEBUG
    value: "true"
```
If there are errors sending the messages you should see them. 

I will be on holiday for the next two weeks so I can not help you any further until then and have no time now to validate the logging to Grafana Cloud myself (there is a small chance that their API changed, breaking the integration). If you are stuck you might try to post a message on the [ha community topic](https://community.home-assistant.io/t/logspout-add-on-for-sending-ha-logs-to-log-management-systems/), maybe someone else will be able to help. Otherwise please remind me in a few weeks.

**Comment by bertbaron** [comment]
Is this still a problem for you? I tried myself and it works for me. On grafana.com, I go to 'My Account', Launch Grafana, go to Explore, select `grafanacloud-<my-username>-logs` (Loki). Then under `label filters` I can select `nodename` and choose `ha` as value.

**Comment by moltob** [comment]
Thanks a lot for checking again. I was considering using Graylog instead, but I'll give it another try. But actually now I am on vacation. So it'll be another two weeks on my end.

Using a local Loki instance worked, but the data was weird in terms of timestamps. But we'll see. I'll keep you posted.

I would prefer using Grafana, so I very much appreciate your test and support!

Picking up testing on my end once I get home.

**Comment by moltob** [comment]
I just retried. Now I do see data coming in. (Don't ask me, why this was not the case in the first attempt...). However, now I see a similar issue to a local Loki instance: It appears the timestamps sent to (or interpreted by) Loki are not the log times, but for some funny reason this seem to be the time logspout was started.

So in my case, all logs sit at this single point in time:

![image](https://github.com/bertbaron/hassio-addons/assets/6240478/2ede0501-58da-4e00-91b2-7659c07394bb)

You can also the see the "wrong" and the "real" timestamps in the textual logs. Here some random examples logs:

![image](https://github.com/bertbaron/hassio-addons/assets/6240478/893c1401-449a-4a54-a490-2b99e89d2abf)

When I show the labels of the first entry, the created date even shows this is a much older entry:

![image](https://github.com/bertbaron/hassio-addons/assets/6240478/ace935d7-f9d4-452b-b14b-aae910f1dbf1)

Here is another log entry that was just emitted:

![image](https://github.com/bertbaron/hassio-addons/assets/6240478/53907698-2eb4-4031-8d25-882875e66d4c)

Am I missing a timestamp mapping somewhere?

**Comment by bertbaron** [comment]
You are right, that is a bug indeed! Never noticed it, and I wonder if anyone uses the Loki adapter. But I wil fix this asap.

**Comment by bertbaron** [comment]
I just created a new release which includes a fix for the timestamps in the Loki adapter

**Comment by moltob** [comment]
Thank you so much, it is working now! I'll keep using Grafana now as originally intended. I'll let you know if I stumble across other issues, if I may.

Feel free to close the issue whenever it suits you.
