### ISSUE TITLE
[Feature Request] Add support for Splunk HEC

### ISSUE THREAD

**Issue by stboch** [bertbaron/hassio-addons#68]
Someone has already built a logspout module. 
I'm looking to get nice JSON formatting versus the existing syslog method.
https://github.com/chakrabortymrinal/logspout-splunk

**Comment by bertbaron** [comment]
I just released a version with the Splunk Adapter added. Note that I didn't perform any tests from my side. Please let me know if this works for you.

**Comment by stboch** [comment]
Sorry for the delay. Holidays and life got the best of me.
Tested and works great.
Unless the user has a valid cert (probably not in a home lab but who knows... user needs to add SPLUNK_INSECURE amongst the other settings, additionally the code is hard configured to require HEC to use SSL if a user isn't using SSL on their HEC endpoint this is also fail.
Recommended ENV fields:
`- name: SPLUNK_TOKEN
  value: (Splunk HEC Token)
- name: SPLUNK_INSECURE
  value: "true"
- name: SPLUNK_INDEX
  value: (index in splunk)`

**Comment by bertbaron** [comment]
Thanks for the update, I'll add that to the documentation.

**Comment by johnciavarella** [comment]
I came here from the docs as it was the reference for Splunk routes out. What is the format for the Splunk route? @stboch

**Comment by stboch** [comment]
I configured it as multiline+splunk://splunkurl:port/

However it does require https port for splunk's HEC to be configured.

**Comment by johnciavarella** [comment]
I was trying `splunk+https://<SERVER>:<PORT>/services/collector/event?token=<TOKEN>` cobbled together from some places, as Im not familiar logspout.

**Comment by stboch** [comment]
@johnciavarella https:// is not used. And neither is the collector info. The token information is consumed as part of the environment settings see previous comment.
